services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Admin\Administration\UserAdmin:
        arguments:
            - ~
            - App\Entity\User
            - App\Controller\CRUDUserController
        tags:
            - { name: sonata.admin, manager_type: orm, group: user, label: "administration_user", label_translator_strategy: "App\\Translator\\ProjectLabelTranslatorStrategy" }